In [1]:
import pandas as pd

In [2]:
population2020_2029 = pd.read_csv('./population_data/population-2020-2029.csv')
population2020_2029.head()

,LocID,Location,Time,AgeGrp,AgeGrpStart,AgeGrpSpan,PopMale,PopFemale,PopTotal
0,4,Afghanistan,2020,0-4,0,5,2907.406,2765.103,5672.509
1,8,Albania,2020,0-4,0,5,86.564,79.714,166.278
2,12,Algeria,2020,0-4,0,5,2574.062,2467.456,5041.518
3,24,Angola,2020,0-4,0,5,2923.514,2871.49,5795.004
4,28,Antigua and Barbuda,2020,0-4,0,5,3.73,3.625,7.355